# Generated by Django 3.2.13 on 2022-07-10 07:12

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=25)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ArteCriollo', max_length=25)),
                ('logo', models.ImageField(default='/static/images/logo.png', upload_to='image/logo')),
                ('icon', models.ImageField(default='/static/images/logo.png', upload_to='image/icon')),
                ('email', models.EmailField(default='artecriollocuba@gmail.com', max_length=30)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(default='+5351183924', max_length=11)),
                ('mobile', models.CharField(default='+5351183924', max_length=11)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='image/socialred/icon')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image/socialred/logo')),
                ('name', models.CharField(max_length=25)),
                ('name_user', models.CharField(max_length=25)),
                ('url', models.URLField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GROUP_USER', 'GROUP_USER'), ('ALL_USER', 'ALL_USER'), ('ONE_USER', 'ONE_USER'), ('ALL_USER_AUTHENTICATED', 'ALL_USER_AUTHENTICATED')], max_length=22)),
                ('message', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('readed_at', models.DateTimeField(blank=True, null=True)),
                ('readed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('readed_for', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
