# Generated by Django 3.2.13 on 2022-07-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_notificationuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='type',
            field=models.CharField(choices=[('ALL_USER', 'ALL_USER'), ('ONE_USER', 'ONE_USER'), ('GROUP_USER', 'GROUP_USER'), ('ALL_USER_AUTHENTICATED', 'ALL_USER_AUTHENTICATED')], max_length=22),
        ),
    ]
