# Generated by Django 3.2.13 on 2022-07-10 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(blank=True, to='shop.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Libraries',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido(s)')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=80, null=True)),
                ('profile_info', models.TextField(blank=True, max_length=150, null=True, verbose_name='Sobre ti')),
                ('created', models.DateField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Teléfono')),
                ('ci', models.CharField(blank=True, max_length=11, null=True, verbose_name='Carnet de Identidad')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(blank=True, choices=[('HOMBRE', 'HOMBRE'), ('MUJER', 'MUJER'), ('OTRO', 'OTRO')], max_length=6, null=True, verbose_name='Género')),
                ('affiliated', models.BooleanField(blank=True, default=False, null=True)),
                ('affiliated_url', models.CharField(blank=True, max_length=30, null=True)),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to=settings.AUTH_USER_MODEL)),
                ('recommended_digital_products', models.ManyToManyField(blank=True, to='shop.Product')),
                ('recommended_products', models.ManyToManyField(blank=True, to='shop.Order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('whishlist', models.ManyToManyField(blank=True, related_name='whishlist_user', to='shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('people', models.ManyToManyField(related_name='people_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aprovated', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.profile')),
            ],
        ),
    ]
